# Generated by Django 5.2.5 on 2025-09-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
