# Generated by Django 5.2.5 on 2025-09-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogpost_document_blogpost_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='email',
            new_name='website',
        ),
    ]
