# Generated by Django 5.2.5 on 2025-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_email_blogpost_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='blog_document/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog_picture/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='ვებ მისამართი'),
        ),
    ]
