# Generated by Django 5.2.5 on 2025-09-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogpost_options_remove_blogpost_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['title'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog_app.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog_app.author'),
        ),
    ]
