# Generated by Django 5.2.5 on 2025-09-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_author_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_image/')),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='blog_app.blogpost')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['id'],
            },
        ),
    ]
