# Generated by Django 5.2.5 on 2025-09-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_bannerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
