# Generated by Django 5.2.5 on 2025-09-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog_app.author'),
        ),
    ]
