# Generated by Django 5.2.5 on 2025-09-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_blogpost_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='დაბადების თარიღი'),
        ),
    ]
