# Generated by Django 5.2.5 on 2025-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='წაშლილია'),
        ),
    ]
