# Generated by Django 5.2.5 on 2025-09-10 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_blogpost_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='create_date_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='შექმნის თარიღი'),
            preserve_default=False,
        ),
    ]
