# Generated by Django 5.2.5 on 2025-09-15 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_blogpost_create_date_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bannerimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpostimage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='blog_app.blogpost'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(default='banner_images/default.jpg', upload_to='banner_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(to='blog_app.author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='create_date_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='document',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='website',
        ),
    ]
