# Generated by Django 5.2.5 on 2025-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_author_options_alter_bannerimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
