# Generated by Django 5.2.5 on 2025-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_blogpost_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
