# Generated by Django 5.2.5 on 2025-09-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_blogpost_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['order']},
        ),
    ]
