# Generated by Django 5.2.5 on 2025-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='blog_document/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default='', verbose_name='ტექსტი'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.URLField(null=True, verbose_name='ვებ მისამართი'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='აქტიურია'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='წაშლილია'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='სათაური'),
        ),
    ]
