# Generated by Django 5.2.5 on 2025-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_blogpost_document_blogpost_text_blogpost_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='ტექსტი'),
        ),
    ]
