# Generated by Django 5.2.5 on 2025-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_blogpost_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
