# Generated by Django 5.2.5 on 2025-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_alter_blogpostimage_options_blogpostimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='authors',
            field=models.ManyToManyField(related_name='images', to='blog_app.author'),
        ),
    ]
