# Generated by Django 5.2.5 on 2025-09-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_blogpostimage_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'ordering': ['order'], 'verbose_name': 'Banner image', 'verbose_name_plural': 'Banner images'},
        ),
        migrations.AlterModelOptions(
            name='blogpostimage',
            options={'ordering': ['order'], 'verbose_name': 'Blog post image', 'verbose_name_plural': 'Blog post images'},
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='blog_app.blogpost', verbose_name='Blog post'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='banner_images/', verbose_name='ბანერის სურათი'),
        ),
        migrations.CreateModel(
            name='BlogPostImageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='blog_app.blogpostimage', verbose_name='Blog post image')),
            ],
            options={
                'verbose_name': 'Blog post image Description',
                'verbose_name_plural': 'Blog post images Descriptions',
            },
        ),
    ]
