# Generated by Django 5.2.5 on 2025-09-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_bannerimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimagedescription',
            old_name='blog_post',
            new_name='blog_post_image',
        ),
    ]
